server {
    listen 80;
    server_name sims3.hansollvina.com sims.hansollvina.com;

    access_log /var/log/nginx/sims/access.log main;
    error_log  /var/log/nginx/sims/error.log;

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location / {
        proxy_pass http://192.168.98.27:8888;
        include /etc/nginx/snippets/proxy-common.conf;
        
    }
}

server {
    listen 443 ssl;
    server_name sims3.hansollvina.com sims.hansollvina.com sims2.hansollvina.com;

    ssl_certificate     /etc/letsencrypt/live/sims3.hansollvina.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/sims3.hansollvina.com/privkey.pem;

    access_log /var/log/nginx/sims/access.log main;
    error_log  /var/log/nginx/sims/error.log;

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location / {
        proxy_pass http://192.168.98.27:8888;
        include /etc/nginx/snippets/proxy-common.conf;
        
    }
}
