version = 5.7.0
archive_dir = /etc/letsencrypt/archive/subcon3.hansollvina.com
cert = /etc/letsencrypt/live/subcon3.hansollvina.com/cert.pem
privkey = /etc/letsencrypt/live/subcon3.hansollvina.com/privkey.pem
chain = /etc/letsencrypt/live/subcon3.hansollvina.com/chain.pem
fullchain = /etc/letsencrypt/live/subcon3.hansollvina.com/fullchain.pem
[renewalparams]
account = 523261e9891dbae0e6a5397ba9f9a531
authenticator = webroot
webroot_path = /var/www/certbot,
server = https://acme-v02.api.letsencrypt.org/directory
key_type = ecdsa
[[webroot_map]]
subcon3.hansollvina.com = /var/www/certbot
subcon.hansollvina.com = /var/www/certbot
