events {}

http {

    server {

        listen 9010;

        location /web1/ {
            proxy_pass http://web1:9011/;
        }

        location /web2/ {
            proxy_pass http://web2:9012/;
        }

        location /web3/ {
            proxy_pass http://web2:9013/;
        }

    }

}

