services:
  postgres:
    image: postgres:17
    environment:
      POSTGRES_DB: employee_db
      POSTGRES_USER: employee_user
      POSTGRES_PASSWORD: employee_pass
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app-network

  web6:
    build: ./web6
    ports:
      - "9061:9061"
    environment:
      DATABASE_URL: postgresql+psycopg://employee_user:employee_pass@postgres:5432/employee_db
    depends_on:
      - postgres
    networks:
      - app-network

volumes:
  postgres-data:

networks:
  app-network: