events {}

http {

    server {

        listen 9000;

        location /web1/ {
            proxy_pass http://web1:9001/;
        }

        location /web2/ {
            proxy_pass http://web2:9002/;
        }

    }

}

