services:

  web1:
    build: ./web1
    container_name: bai04_web1
    ports:
      - "9011:9011"
    networks:
      - web-network

  web2:
    build: ./web2
    container_name: bai04_web2
    ports:
      - "9012:9012"
    networks:
      - web-network

  nginx:
    build: ./nginx
    container_name: bai04_nginx
    ports:
      - "9010:9010"
    networks:
      - web-network
      
networks:
  web-network: