events {}

http {

    server {

        listen 9110;

        location /web1/ {
            proxy_pass http://web1:9111/;
        }

        location /web2/ {
            proxy_pass http://web2:9112/;
        }
        
        location /web3/ {
            proxy_pass http://web3:9113/;
        }

    }

}

